### ISSUE TITLE
Can't delete file with leading dot in the name

### ISSUE THREAD

**Issue by kborowinski** [perrada69/CalmCommander#1]
@perrada69 :
Can't delete file with leading dot in the name

**Steps to reproduce:**

1. Create file with leading dot in the name:
```.test```
2. Cannot delete the *.test* file from CalmCommander

**Expected behavior:**

Users should be able to delete file with any name from CalmCommander

**Comment by perrada69** [comment]
Hello,

I tried to delete the dotted file at the beginning and the file was deleted. I renamed a file to .test and went to delete it as well. I copied the dot files in the name from the PC and also went to delete them in CalmCommander.

What version of CalmCommander are you using?

**Comment by kborowinski** [comment]
I'm using latest github build (0.2) but apparently it's not related to CC but FlashAIR SD card (one when you can copy files over WiFi). I can't delete or rename freshly copied files until I remount the drive on Next. Sorry for false positive, you can close the issue now.
