### ISSUE TITLE
Screen Rendering Issues

### ISSUE THREAD

**Issue by andymccall** [perrada69/CalmCommander#2]
System Information: ZX Spectrum Next
Raspberry Pi Accelerator Present: Yes
RTC: Yes
Wifi: Yes
Memory: 2MB
Firmware: 1.2.9b
Core: 3.01.5
Graphics Mode: 7/60Hz/scan*2
Display Connection Type: HDMI
Display: Samsung T24E390
MicroSD Card: Default one issued with pack
Other information: MicroSD connected via extension cable.  ActiveConsult control pad connected.

Actions to reproduce error:

- Format MicroSD with SD Association SD Card Formatter
- Copy contents of of sn-complete-v.1.3.2.zip to SD card
- Create apps folder on root of MicroSD
- Copy CalmComander.nex to apps folder
- Boot ZX Spectrum Next, holding down D
- Choose screen mode of 7/60Hz/scan*2
- Clock through first boot display
- Choose Browser
- Chose Apps->CalmComander.nex

The screen is rendered incorrectly.  The menu is missing on the display:

![image](https://user-images.githubusercontent.com/11350104/81917195-c89fbc00-95cc-11ea-9f72-550184bb0222.png)

Workaround: Set the screen mode to 7/50Hz/scan*2.  This will render the screen correctly, although some displays may not allow this refresh rate and make this workaround unusable.

**Comment by perrada69** [comment]
Hi, but this is problem monitor, right? 

maybe I can switch views to another view. I try it and write you and send test file, ok?

**Comment by ped7g** [comment]
Each monitor can have different "overscan" area. There's `.displayedge` tool in distro so the user can set the visible frame in each mode and store that in `/sys/env.cfg` file, then any other tool can hypothetically read the config, and adjust display output, i.e. you need to write CC in such way, that you can display at 80x32 or 76x24 (or 80x42 with the 8x6px tiles :) ) ...

... but that's not 1-2 line change, especially if you don't plan for it from start, so I guess for the moment 50Hz mode + good display is the answer.

**Comment by andymccall** [comment]
Ah!

50Hz does indeed work on my display.  This is a good temporary workaround until / if 60Hz is ever added.

**Comment by ped7g** [comment]
I'm sure any decent Next SW should support this and read the displayedge config, but the "calm commander" total development time is still counted rather in days, so I guess this kind of problems are still acceptable... maybe after few years when it will be in "2.0" and the display will be still hard 80x32, I will raise my eyebrow onto Shrek, wtf is he thinking... :)

**Comment by perrada69** [comment]
Now I'm working on disk operations and other functions, ... then I'll try to solve this problem - if I can simulate it on my monitor. ;)

**Comment by andymccall** [comment]
> Now I'm working on disk operations and other functions, ... then I'll try to solve this problem - if I can simulate it on my monitor. ;)

You should be able to simulate a vastly under-scanned area on your display via the displayedge config and get it working on your setup that way, then I can test on mine @60Hz.
